name: RACV UI - CI/CD

on:
  push:
    branches: ["main"]

env:
  APP_NAME: racv-ui
  APP_ROOT: /opt/racv-ui
  NODE_VERSION: "20"
  VM_USERNAME: redeautocvuser
  VM_IP: 74.235.237.161
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Package build folder
        run: |
          ls -l
          tar -czf build.tar.gz dist

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_KEY_001 }}" > ~/deploy_key.pem
          chmod 400 ~/deploy_key.pem

      - name: Upload build
        run: |
          scp -i ~/deploy_key.pem -o StrictHostKeyChecking=no \
            build.tar.gz \
            ${{ env.VM_USERNAME }}@${{ env.VM_IP }}:~/

      - name: Deploy on server
        run: |
          ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no \
            ${{ env.VM_USERNAME }}@${{ env.VM_IP }} << 'EOF'
          set -e

          APP_ROOT=/opt/racv-ui
          RELEASE=$(date +%Y%m%d%H%M%S)

          mkdir -p $APP_ROOT/releases
          mkdir -p $APP_ROOT/shared

          mv ~/build.tar.gz $APP_ROOT/releases/$RELEASE.tar.gz
          cd $APP_ROOT/releases
          mkdir $RELEASE
          tar -xzf $RELEASE.tar.gz -C $RELEASE
          rm $RELEASE.tar.gz

          ln -sfn $APP_ROOT/releases/$RELEASE/build $APP_ROOT/current

          sudo systemctl reload nginx
          EOF
